version: '3'
services:
  centos-test:
    build:
      context: ./centos
    container_name: centos-test
    working_dir: /
    privileged: true
    volumes:
      - ./data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 8088:80
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    external:
      name: vietjack-app-network
